# Generated by Django 5.2.11 on 2026-04-10 14:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='imię')),
                ('last_name', models.CharField(max_length=100, verbose_name='nazwisko')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s\\-]{7,20}$', 'Podaj poprawny numer telefonu (cyfry, spacje, myślniki, opcjonalnie +).')], verbose_name='telefon')),
            ],
            options={
                'verbose_name': 'podróżnik',
                'verbose_name_plural': 'podróżnicy',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=200, verbose_name='cel podróży')),
                ('description', models.TextField(blank=True, verbose_name='opis')),
                ('start_date', models.DateField(verbose_name='data rozpoczęcia')),
                ('end_date', models.DateField(verbose_name='data zakończenia')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='cena (PLN)')),
                ('max_participants', models.PositiveIntegerField(default=10, verbose_name='maks. uczestników')),
            ],
            options={
                'verbose_name': 'wycieczka',
                'verbose_name_plural': 'wycieczki',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='data dodania')),
                ('status', models.CharField(choices=[('pending', 'Oczekująca'), ('confirmed', 'Potwierdzona'), ('cancelled', 'Anulowana')], default='pending', max_length=20, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='uwagi')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='travels.traveler', verbose_name='podróżnik')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='travels.trip', verbose_name='wycieczka')),
            ],
            options={
                'verbose_name': 'rezerwacja',
                'verbose_name_plural': 'rezerwacje',
                'ordering': ['-created_at'],
                'unique_together': {('trip', 'traveler')},
            },
        ),
    ]
